// Generated by LiveScript 1.3.1
(function(){
  var directives;
  directives = angular.module('spore-ui.directives', []);
  directives.directive("formMethod", function(){
    return {
      restrict: "E",
      templateUrl: "form-method.html"
    };
  });
  directives.directive("pageSearch", function(){
    return {
      restrict: "E",
      templateUrl: "page-search.html"
    };
  });
  directives.directive("pageResults", function(){
    return {
      restrict: "E",
      templateUrl: "page-results.html"
    };
  });
  directives.directive("listResults", function(){
    return {
      restrict: "E",
      templateUrl: "list-results.html"
    };
  });
}).call(this);
